### ISSUE TITLE
Won't compile with node v7.5

### ISSUE THREAD

**Issue by PipelineBaron** [nikhilm/node-taglib#21]
`../src/tag.cc:239: error: ‘Loop’ was not declared in this scope`

`node::Loop()` no longer exists in node latest. It's purpose was to support isolates in node.js. The isolate support project has been canceled in node core and as a result `node::loop()` no longer exists in node.h

The fix is a simple one liner. Just replace `Loop()` on line 239 of src/tag.cc with `uv_default_loop()` and this library will compile with node v7.5
